name: Test module
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  # ------------------------------------------------------------------------------
  # This job builds the 787, and uploads an artifact
  # ------------------------------------------------------------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          dest: "./res/"
          version: "v1.9.0"
