name: Test module
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          dest: "./res/"
          version: "v1.9.0"
      - uses: ./
        with:
          dest: "./res/"
          version: "v1.34.0"
          branch: "marty"
      - uses: actions/upload-artifact@v2
        with:
          name: Results
          path: "./res/"
